/**
 * Complete list of technologies displayed in the typewriter animation.
 * Extracted from the skills data in resume.json.
 */
export const TECHNOLOGY_LABELS = [
  "JavaScript",
  "Python",
  "C#",
  "React.js",
  "Angular",
  "Vue.js",
  "Next.js",
  "Nuxt.js",
  "TypeScript",
  "jQuery",
  "Styled Components",
  "Tailwind CSS",
  "Bootstrap",
  "Express",
  "Prisma",
  "Socket.io",
  "Nest.js",
  "Django",
  "Flask",
  "Entity Framework",
  "AutoMapper",
  "Moq",
  "xUnit",
  "PostgreSQL",
  "MySQL",
  "Microsoft SQL Server",
  "MongoDB",
  "Figma",
  "Canva",
  "Postman",
  "DevTools",
  "Jest",
  "Selenium",
  "Scrapy",
  "GitHub Actions",
  "Azure DevOps",
  "Docker",
  "Ansible",
  "NGINX",
  "RabbitMQ",
] as const;
